### ISSUE TITLE
[FEATURE] Real-time updates via webhooks

### ISSUE THREAD

**Issue by alpenhannes** [Challengermode/public-api-issues#1]
**Describe the feature you're missing.**
Real-time data updates! I want to know the second a team wins a game in a tournament so that I can show live brackets on my website and in my live broadcast for 139.500 viewers on Turkish television. 

**Is your feature request related to a problem? Please describe.**
Right now, I need to call the API in regular intervals to see if any updates have occurred. With how deep the information in tournaments goes, this can take tens of calls before I get to live scores which makes it both complicated and resource-intensive for myself and you.

**Proposed solutions.**
To avoid exceeding rate limits (and to protect your infrastructure from overloading), I would love to connect to webhooks that push updates to me when they occur.

**Comment by philipshield** [comment]
This is now supported through GraphQL subscriptions in the new [Challengermode Client API](https://www.challengermode.com/developers/docs/challengermode-api)! 
Closing this issue.
