### ISSUE TITLE
[FEATURE] API Request with join Tables  (?with=matches,users.....)

### ISSUE THREAD

**Issue by Dandrum** [Challengermode/public-api-issues#2]
**Describe the feature you're missing.**
At the moment when i fetch a whole tournament i need to fetch the tournament, the bracket, matches, member, user and so on all separate instead of a single call.

**Is your feature request related to a problem? Please describe.**
No Problem just nice to have easier fetching

**Proposed solutions.**
Add a ?with or ?add or something to the fetchURL Like 
``` https://xxxx/api/xxx?with=machtes,members,brackets``` 
to receive a filled tournament with all information for the initial call, after that i update parts of it with the single endpoints from time to time. For example 
``` https://xxx/v1/tournaments/match_series/{id}?with=lineups,members,matches ```

That would reduce the amount of calls and helps much.

Best,
Dan

**Comment by xobust** [comment]
Sorry for the late update. 
This feature is not something we have on the roadmap, but the [Tournament Graph](https://www.challengermode.com/developers/docs/mk1/reference/api/v1/Tournaments#/v1/tournaments/{id}/graph) API has a similar purpose.
It allows you to fetch most of the tournaments data in one API call. 
Let me know if you have any feedback on it.

**Comment by yannickgloster** [comment]
@xobust, will the Graph type API be coming to other models like user?

**Comment by Dandrum** [comment]
Sounds interesting i will look into it and give some response.

**Comment by Dandrum** [comment]
Ok that works pretty good and i get most of the information by one call and then to fill up userdata for ervery user i call user endpoint if needed. Thans a lot
