### ISSUE TITLE
[FEATURE] SteamID32 in user "externalLogins"

### ISSUE THREAD

**Issue by Dandrum** [Challengermode/public-api-issues#4]
Many users have Steam linked to Profile (in my case dota tournaments)  but in the User/externalLogins array are only uids to fetch the external login extra but there is no endpoint for fetching. In my case i want to enrich the user with additional information form Dota API.

**Proposed solutions.**
Add SteamID32 to externalLogins or let us fetch SteamID / User account id.

**Comment by xobust** [comment]
Hey sorry for the late update, we could add steam as an external login on the user but it would not always be the same steamId used to compete in a tournament as the player can unlink or change the account. 
To make sure that it is easy to identify the external Id of a tournament participant we are also considering adding a GameAccount resource or exposing the ExternalGameAccountId (eg steamId) in the match data.

**Comment by Dandrum** [comment]
Its fine if the user change the steamId i will update them if necessary. I already build a small js lib to fetch tournament data from you api and caching it to prevent to api calls. We tell our Players to link their Steam Id because in our case we use the Dota Auto invite feature.

**Comment by xobust** [comment]
SteamId64 added to user ExternalLogins
